PREFIX base: <http://purl.obolibrary.org/obo/UBERON_>
SELECT ?nodes ?edges ?edge_types
WHERE {
  {
    SELECT (COUNT(DISTINCT(?s)) as ?nodes)
    WHERE {
      { ?s ?p1 [] . }
      UNION
      { [] ?p2 ?s . FILTER(isIRI(?s)) }
      FILTER(STRSTARTS(STR(?s), STR(base:)))
    }
  }
  {
    SELECT (COUNT(*) as ?edges)
    WHERE { ?s ?p ?o . FILTER(STRSTARTS(STR(?s), STR(base:)) || STRSTARTS(STR(?p), STR(base:))) }
  }
  {
    SELECT (COUNT(DISTINCT(?p)) as ?edge_types)
    WHERE { ?s ?p ?o . }
  }
}